version: "3"

services:
  nextjs:
    # TODO: change all label `projectname`
    container_name: projectname-nextjs
    # TODO: set your repo here
    image: ghcr.io/user/repository:deploy
    restart: unless-stopped
    volumes:
      - ./cache/images:/app/.next/cache/images
    env_file: .env
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.projectname-nextjs.tls=true
      - traefik.http.routers.projectname-nextjs.entrypoints=websecure
      - traefik.http.routers.projectname-nextjs.tls.certresolver=letsencrypt
      - traefik.http.services.projectname-nextjs.loadbalancer.server.port=3000
      # TODO: set your domain here
      - traefik.http.routers.projectname-nextjs.rule=Host(`www.yourdomain.com`) || Host(`yourdomain.com`)

      # TODO : select this if you want redirect from non-www to www
      # - traefik.http.routers.projectname-nextjs.middlewares=redirect-to-www
      # - traefik.http.middlewares.redirect-to-www.redirectregex.regex=^https?://yourdomain.com/(.*)
      # - traefik.http.middlewares.redirect-to-www.redirectregex.replacement=https://www.yourdomain.com/$${1}
      # - traefik.http.middlewares.redirect-to-www.redirectregex.permanent=true

      # TODO : or select this if you want redirect from www to non-www
      # - traefik.http.routers.projectname-nextjs.middlewares=redirect-to-non-www
      # - traefik.http.middlewares.redirect-to-non-www.redirectregex.regex=^https?://www.yourdomain.com/(.*)
      # - traefik.http.middlewares.redirect-to-non-www.redirectregex.replacement=https://yourdomain.com/$${1}
      # - traefik.http.middlewares.redirect-to-non-www.redirectregex.permanent=true
    networks:
      - proxy
    expose:
      - 3000

networks:
  proxy:
    external: true
