version: "3"

services:
  payloadcms:
    # TODO: change all label `projectname`
    container_name: projectname-payloadcms
    # TODO: set your repo here
    image: ghcr.io/user/repository:deploy
    restart: unless-stopped
    volumes:
      - ./medias:/app/media
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
    env_file: ./.env
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.projectname-payloadcms.tls=true
      - traefik.http.routers.projectname-payloadcms.tls.certresolver=letsencrypt
      - traefik.http.routers.projectname-payloadcms.entrypoints=websecure
      # TODO: set your domain here
      - traefik.http.routers.projectname-payloadcms.rule=Host(`backend.yourdomain.com`)
      - traefik.http.routers.projectname-payloadcms.service=projectname-payloadcms
      - traefik.http.services.projectname-payloadcms.loadbalancer.server.port=3001
    networks:
      - proxy
      - backend
    expose:
      - 3001
    depends_on:
      - mongo

  mongo:
    container_name: projectname-mongo
    image: mongo:4-bionic
    command:
      - --storageEngine=wiredTiger
    volumes:
      - ./mongodb:/data/db
    networks:
      - backend
    environment:
      # TODO: set database credential
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: databasename

networks:
  proxy:
    external: true
  backend:
